"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 16:22:34.137949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('actor_type', sa.Enum('ADMIN', 'USER', 'SYSTEM', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('default_branch', sa.String(length=64), nullable=False),
    sa.Column('default_lease_duration_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('action_type', sa.Enum('PushEvent', 'PullRequestReviewEvent', 'IssueCommentEvent', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('required_permission', sa.Enum('read', 'write', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_user_id'), ['user_id'], unique=False)

    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('current_role', sa.Enum('read', 'write', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('granted_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo_id', name='uq_lease_user_repo')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leases_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_user_id'), ['user_id'], unique=False)

    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.Enum('read', 'write', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='appealstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('resolved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appeals_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeals_user_id'))
        batch_op.drop_index(batch_op.f('ix_appeals_lease_id'))

    op.drop_table('appeals')
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_user_id'))
        batch_op.drop_index(batch_op.f('ix_leases_repo_id'))

    op.drop_table('leases')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_events_repo_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_team_id'))

    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('repositories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
